name: Automated Test suite using Pytest with Pipenv
# workflow triggered by any push on any branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Pytest in Pipenv
    # runs on the latest Ubuntu
    runs-on: ubuntu-latest 
    # runs within your Docker container
    container:
      image: docker://joydeep-recurve/eemeter:latest
    # checkout your code from your repository
    # and runs pytest in your pipenv environment
    steps:
    - uses: actions/checkout@v2
    - name: Test with pytest
      run: |
          pipenv run pytest tests/
